# Generated by Django 4.2.9 on 2024-02-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, null=True)),
                ('price', models.FloatField(null=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('image', models.ImageField(max_length=50, null=True, upload_to='')),
            ],
        ),
    ]
